#!/usr/bin/env bash

MODE="ReleaseFast"
RUN_TESTS=0

for arg in "$@"; do
	case "$arg" in
		--test)
			RUN_TESTS=1
			;;
		--debug)
			MODE="Debug"
			;;
		*)
			echo "Unknown argument: $arg" >&2
			echo "Usage: ./build [--test] [--debug]" >&2
			exit 1
			;;
	esac
done

if [ "$RUN_TESTS" -eq 1 ]; then
	exec nix develop -c zig build test "-Doptimize=${MODE}"
fi

exec nix develop -c zig build "-Doptimize=${MODE}"
